# Generated by Django 4.1 on 2022-08-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=230)),
                ('legs', models.IntegerField(max_length=230)),
                ('weight', models.IntegerField(max_length=230)),
                ('height', models.IntegerField(max_length=230)),
                ('speed', models.IntegerField(max_length=230)),
                ('family', models.CharField(max_length=230)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=230)),
            ],
        ),
    ]
